//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Campaign {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Campaign() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Campaign", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer berhasil dihapus.
        /// </summary>
        internal static string CampaignCustomerDelete {
            get {
                return ResourceManager.GetString("CampaignCustomerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer berhasil ditambahkan.
        /// </summary>
        internal static string CampaignCustomerSuccess {
            get {
                return ResourceManager.GetString("CampaignCustomerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign berhasil dihapus.
        /// </summary>
        internal static string CampaignDeleteSuccess {
            get {
                return ResourceManager.GetString("CampaignDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead berhasil dihapus.
        /// </summary>
        internal static string CampaignLeadDelete {
            get {
                return ResourceManager.GetString("CampaignLeadDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead berhasil ditambahkan.
        /// </summary>
        internal static string CampaignLeadSuccess {
            get {
                return ResourceManager.GetString("CampaignLeadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing List berhasil dihapus.
        /// </summary>
        internal static string CampaignMarketingListDelete {
            get {
                return ResourceManager.GetString("CampaignMarketingListDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing List berhasil ditambahkan.
        /// </summary>
        internal static string CampaignMarketingListSuccess {
            get {
                return ResourceManager.GetString("CampaignMarketingListSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign berhasil disimpan.
        /// </summary>
        internal static string CampaignSaveSuccess {
            get {
                return ResourceManager.GetString("CampaignSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Campaign Code harus diisi.
        /// </summary>
        internal static string MandatoryCode {
            get {
                return ResourceManager.GetString("MandatoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name harus diisi.
        /// </summary>
        internal static string MandatoryName {
            get {
                return ResourceManager.GetString("MandatoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Product harus dipilih.
        /// </summary>
        internal static string MandatoryProduct {
            get {
                return ResourceManager.GetString("MandatoryProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Campaign Type harus dipilih.
        /// </summary>
        internal static string MandatoryType {
            get {
                return ResourceManager.GetString("MandatoryType", resourceCulture);
            }
        }
    }
}
