//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ESBKeyValueName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ESBKeyValueName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ESBKeyValueName", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountNumber.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_AccountNo1 {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_AccountNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountNumber.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_AccountNo2 {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_AccountNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountNumber.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_AccountNo3 {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_AccountNo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountNumber.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_AccountNo4 {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_AccountNo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerCategory.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_CustomerCategory {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_CustomerCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerId.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_CustomerId {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastCustomerStatusUpdate.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_LastPinChangeDate {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_LastPinChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerStatus.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_LastStatus {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_LastStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeStamp.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_LastUpdateDate {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_LastUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerName.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_Name {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinChangeFlag.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_PinChangeRequired {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_PinChangeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginDate.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_RegistrationDate {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_UpdateByUserGroup {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_UpdateByUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNum.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_UpdateByUserNum {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_UpdateByUserNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BadPinCounter.
        /// </summary>
        internal static string PhoneBankingInquiryStatus_WrongPinCounter {
            get {
                return ResourceManager.GetString("PhoneBankingInquiryStatus_WrongPinCounter", resourceCulture);
            }
        }
    }
}
