//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lead {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lead() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lead", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status lead berhasil diubah.
        /// </summary>
        internal static string LeadChangeStateSuccess {
            get {
                return ResourceManager.GetString("LeadChangeStateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead telah berubah menjadi customer.
        /// </summary>
        internal static string LeadQualifySuccess {
            get {
                return ResourceManager.GetString("LeadQualifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead berhasil disimpan.
        /// </summary>
        internal static string LeadSuccess {
            get {
                return ResourceManager.GetString("LeadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Address harus diisi.
        /// </summary>
        internal static string MandatoryAddress {
            get {
                return ResourceManager.GetString("MandatoryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field City harus diisi.
        /// </summary>
        internal static string MandatoryCity {
            get {
                return ResourceManager.GetString("MandatoryCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Company harus diisi.
        /// </summary>
        internal static string MandatoryCompany {
            get {
                return ResourceManager.GetString("MandatoryCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Country harus diisi.
        /// </summary>
        internal static string MandatoryCountry {
            get {
                return ResourceManager.GetString("MandatoryCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Email harus diisi.
        /// </summary>
        internal static string MandatoryEmail {
            get {
                return ResourceManager.GetString("MandatoryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Firstname harus diisi.
        /// </summary>
        internal static string MandatoryFirstname {
            get {
                return ResourceManager.GetString("MandatoryFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Gender harus dipilih.
        /// </summary>
        internal static string MandatoryGenderCode {
            get {
                return ResourceManager.GetString("MandatoryGenderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Lastname harus diisi.
        /// </summary>
        internal static string MandatoryLastname {
            get {
                return ResourceManager.GetString("MandatoryLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Mobile Phone harus diisi.
        /// </summary>
        internal static string MandatoryMobile {
            get {
                return ResourceManager.GetString("MandatoryMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name harus diisi.
        /// </summary>
        internal static string MandatoryName {
            get {
                return ResourceManager.GetString("MandatoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Topic harus diisi.
        /// </summary>
        internal static string MandatoryTopic {
            get {
                return ResourceManager.GetString("MandatoryTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Mobile harus diisi dengan numerik.
        /// </summary>
        internal static string NumerikMobile {
            get {
                return ResourceManager.GetString("NumerikMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Telephone harus diisi dengan numerik.
        /// </summary>
        internal static string NumerikTelephone {
            get {
                return ResourceManager.GetString("NumerikTelephone", resourceCulture);
            }
        }
    }
}
