//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LetterTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LetterTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LetterTemplate", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File yang dilampirkan Max 5 MB.
        /// </summary>
        internal static string Alert_MaxUploadFiles {
            get {
                return ResourceManager.GetString("Alert_MaxUploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name harus diisi.
        /// </summary>
        internal static string Alert_Name {
            get {
                return ResourceManager.GetString("Alert_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak ada file yang dilampirkan.
        /// </summary>
        internal static string Alert_NoFileAttached {
            get {
                return ResourceManager.GetString("Alert_NoFileAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanya file (.docx) yang boleh dilampirkan.
        /// </summary>
        internal static string Alert_OnlyDocument {
            get {
                return ResourceManager.GetString("Alert_OnlyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silahkan aktifkan ActiveX untuk melanjutkan proses upload.
        /// </summary>
        internal static string Alert_PleaseActivateActiveX {
            get {
                return ResourceManager.GetString("Alert_PleaseActivateActiveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Template berhasil disimpan.
        /// </summary>
        internal static string Alert_Success {
            get {
                return ResourceManager.GetString("Alert_Success", resourceCulture);
            }
        }
    }
}
