//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MarketingList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarketingList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MarketingList", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name harus diisi.
        /// </summary>
        internal static string MandatoryName {
            get {
                return ResourceManager.GetString("MandatoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Purpose harus dipilih.
        /// </summary>
        internal static string MandatoryPurpose {
            get {
                return ResourceManager.GetString("MandatoryPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer berhasil dihapus.
        /// </summary>
        internal static string MarketingListCustomerDelete {
            get {
                return ResourceManager.GetString("MarketingListCustomerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer berhasil ditambahkan.
        /// </summary>
        internal static string MarketingListCustomerSuccess {
            get {
                return ResourceManager.GetString("MarketingListCustomerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing List berhasil dihapus.
        /// </summary>
        internal static string MarketingListDelete {
            get {
                return ResourceManager.GetString("MarketingListDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead berhasil dihapus.
        /// </summary>
        internal static string MarketingListLeadDelete {
            get {
                return ResourceManager.GetString("MarketingListLeadDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead berhasil ditambahkan.
        /// </summary>
        internal static string MarketingListLeadSuccess {
            get {
                return ResourceManager.GetString("MarketingListLeadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing List berhasil disimpan.
        /// </summary>
        internal static string MarketingListSuccess {
            get {
                return ResourceManager.GetString("MarketingListSuccess", resourceCulture);
            }
        }
    }
}
