//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotifResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotifResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NotifResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Account No harus diisi.
        /// </summary>
        internal static string AcctNoEmpty {
            get {
                return ResourceManager.GetString("AcctNoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field tanggal harus diisi.
        /// </summary>
        internal static string BlankDate {
            get {
                return ResourceManager.GetString("BlankDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Branch harus diisi.
        /// </summary>
        internal static string BranchBlank {
            get {
                return ResourceManager.GetString("BranchBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Branch harus diisi.
        /// </summary>
        internal static string BranchReportBlank {
            get {
                return ResourceManager.GetString("BranchReportBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Business Unit harus diisi.
        /// </summary>
        internal static string BusinessUnitBlank {
            get {
                return ResourceManager.GetString("BusinessUnitBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apakah anda yakin untuk menonaktifkan user ini?.
        /// </summary>
        internal static string ConfirmDisableUser {
            get {
                return ResourceManager.GetString("ConfirmDisableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apakah anda yakin untuk mengaktifkan user ini?.
        /// </summary>
        internal static string ConfirmEnableUser {
            get {
                return ResourceManager.GetString("ConfirmEnableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field fullname, birthdate, gender harus diisi semua.
        /// </summary>
        internal static string ContactAllFieldsNeeded {
            get {
                return ResourceManager.GetString("ContactAllFieldsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field CIS Number harus diisi.
        /// </summary>
        internal static string ContactCISNeeded {
            get {
                return ResourceManager.GetString("ContactCISNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field parameter produk harus diisi.
        /// </summary>
        internal static string ContactEbankingParameterNeeded {
            get {
                return ResourceManager.GetString("ContactEbankingParameterNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field parameter produk harus diisi.
        /// </summary>
        internal static string ContactProductParameterNeeded {
            get {
                return ResourceManager.GetString("ContactProductParameterNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Corp ID Harus Diisi.
        /// </summary>
        internal static string CorpIdEmpty {
            get {
                return ResourceManager.GetString("CorpIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data tidak ditemukan.
        /// </summary>
        internal static string DataCustomerNotFound {
            get {
                return ResourceManager.GetString("DataCustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data tidak ditemukan.
        /// </summary>
        internal static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data tidak ditemukan.
        /// </summary>
        internal static string DataRequestNotFound {
            get {
                return ResourceManager.GetString("DataRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data sudah berhasil disimpan.
        /// </summary>
        internal static string DataSuccess {
            get {
                return ResourceManager.GetString("DataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data tidak ditemukan.
        /// </summary>
        internal static string DataUserNotFound {
            get {
                return ResourceManager.GetString("DataUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanggal harus diisi.
        /// </summary>
        internal static string DateReportMandatory {
            get {
                return ResourceManager.GetString("DateReportMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koneksi time-out, silakan lakukan pencarian ulang.
        /// </summary>
        internal static string DBTimeout {
            get {
                return ResourceManager.GetString("DBTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Domain Name Harus Diisi.
        /// </summary>
        internal static string DomainNameEmpty {
            get {
                return ResourceManager.GetString("DomainNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID sudah terdaftar.
        /// </summary>
        internal static string DomainNameExistinCRM {
            get {
                return ResourceManager.GetString("DomainNameExistinCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID tidak terdaftar pada domain.
        /// </summary>
        internal static string DomainNameNotFoundAD {
            get {
                return ResourceManager.GetString("DomainNameNotFoundAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Email harus diisi.
        /// </summary>
        internal static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Firstname harus diisi.
        /// </summary>
        internal static string FirstNameBlank {
            get {
                return ResourceManager.GetString("FirstNameBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Inputan Harus Lengkap.
        /// </summary>
        internal static string IncompleteForm {
            get {
                return ResourceManager.GetString("IncompleteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format tanggal salah.
        /// </summary>
        internal static string IncorrectDateFormat {
            get {
                return ResourceManager.GetString("IncorrectDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format bilangan salah.
        /// </summary>
        internal static string IncorrectNumberFormat {
            get {
                return ResourceManager.GetString("IncorrectNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field parameter produk harus diisi.
        /// </summary>
        internal static string InquiryByProduct {
            get {
                return ResourceManager.GetString("InquiryByProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Request ID harus diisi.
        /// </summary>
        internal static string InquiryByRequestId {
            get {
                return ResourceManager.GetString("InquiryByRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID atau Password salah.
        /// </summary>
        internal static string InvalidCredential {
            get {
                return ResourceManager.GetString("InvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak berhak mengakses aplikasi ini. \nHarap hubungi Administrator.
        /// </summary>
        internal static string InvalidUserAccess {
            get {
                return ResourceManager.GetString("InvalidUserAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Lastname harus diisi.
        /// </summary>
        internal static string LastNameBlank {
            get {
                return ResourceManager.GetString("LastNameBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword Harus diisi.
        /// </summary>
        internal static string MandatoryKeyword {
            get {
                return ResourceManager.GetString("MandatoryKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak berhak mengakses menu ini. \nHarap hubungi Administrator.
        /// </summary>
        internal static string MenuNotAllowedToAccess {
            get {
                return ResourceManager.GetString("MenuNotAllowedToAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter harus diisi.
        /// </summary>
        internal static string MustInputParam {
            get {
                return ResourceManager.GetString("MustInputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege Exception tidak berhasil ditambahkan karena ada data yang berlawanan pada field isInclusive.
        /// </summary>
        internal static string PrivilegeExceptionCross {
            get {
                return ResourceManager.GetString("PrivilegeExceptionCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege Exception berhasil dihapus.
        /// </summary>
        internal static string PrivilegeExceptionDelSuccess {
            get {
                return ResourceManager.GetString("PrivilegeExceptionDelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege Exception sudah pernah dibuat.
        /// </summary>
        internal static string PrivilegeExceptionSame {
            get {
                return ResourceManager.GetString("PrivilegeExceptionSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege Exception berhasil disimpan.
        /// </summary>
        internal static string PrivilegeExceptionSuccess {
            get {
                return ResourceManager.GetString("PrivilegeExceptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field address harus diisi.
        /// </summary>
        internal static string RequestMandatoryAddress {
            get {
                return ResourceManager.GetString("RequestMandatoryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field address1 harus diisi.
        /// </summary>
        internal static string RequestMandatoryAddress1 {
            get {
                return ResourceManager.GetString("RequestMandatoryAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field address2 harus diisi.
        /// </summary>
        internal static string RequestMandatoryAddress2 {
            get {
                return ResourceManager.GetString("RequestMandatoryAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field category harus diisi.
        /// </summary>
        internal static string RequestMandatoryCategory {
            get {
                return ResourceManager.GetString("RequestMandatoryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field channel harus diisi.
        /// </summary>
        internal static string RequestMandatoryChannel {
            get {
                return ResourceManager.GetString("RequestMandatoryChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field city harus diisi.
        /// </summary>
        internal static string RequestMandatoryCity {
            get {
                return ResourceManager.GetString("RequestMandatoryCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field customer harus diisi.
        /// </summary>
        internal static string RequestMandatoryCustomer {
            get {
                return ResourceManager.GetString("RequestMandatoryCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field parameter product harus diisi.
        /// </summary>
        internal static string RequestMandatoryCustomerProduct {
            get {
                return ResourceManager.GetString("RequestMandatoryCustomerProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field phone harus diisi.
        /// </summary>
        internal static string RequestMandatoryPhone {
            get {
                return ResourceManager.GetString("RequestMandatoryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field product harus diisi.
        /// </summary>
        internal static string RequestMandatoryProduct {
            get {
                return ResourceManager.GetString("RequestMandatoryProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field summary harus diisi.
        /// </summary>
        internal static string RequestMandatorySummary {
            get {
                return ResourceManager.GetString("RequestMandatorySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field zip harus diisi.
        /// </summary>
        internal static string RequestMandatoryZip {
            get {
                return ResourceManager.GetString("RequestMandatoryZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keluhan Nasabah sudah berhasil disimpan.
        /// </summary>
        internal static string RequestSuccess {
            get {
                return ResourceManager.GetString("RequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keluhan ini hanya dapat di proses melalui Halo BCA.
        /// </summary>
        internal static string RequestWorkgroup {
            get {
                return ResourceManager.GetString("RequestWorkgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field zip harus  5 digit numerik.
        /// </summary>
        internal static string RequestZipLength {
            get {
                return ResourceManager.GetString("RequestZipLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Role harus diisi.
        /// </summary>
        internal static string RoleBlank {
            get {
                return ResourceManager.GetString("RoleBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data berhasil disimpan.
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurityRole berhasil disimpan.
        /// </summary>
        internal static string SecurityRoleSuccess {
            get {
                return ResourceManager.GetString("SecurityRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field SN Token Harus Diisi.
        /// </summary>
        internal static string SnTokenEmpty {
            get {
                return ResourceManager.GetString("SnTokenEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batas maksimum nilai traksaksi adalah 100.000.000.000.
        /// </summary>
        internal static string TransactionAmountRange {
            get {
                return ResourceManager.GetString("TransactionAmountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID sudah berhasil diaktifkan.
        /// </summary>
        internal static string UserActivate {
            get {
                return ResourceManager.GetString("UserActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID sudah berhasil dinonaktifkan.
        /// </summary>
        internal static string UserDeactivate {
            get {
                return ResourceManager.GetString("UserDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field User ID Harus Diisi.
        /// </summary>
        internal static string UserIdEmpty {
            get {
                return ResourceManager.GetString("UserIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID sudah berhasil disimpan.
        /// </summary>
        internal static string UserSuccess {
            get {
                return ResourceManager.GetString("UserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Domain Login name salah. \nContoh : bcadomain\\namauserdomain.
        /// </summary>
        internal static string WrongDomainNameFormat {
            get {
                return ResourceManager.GetString("WrongDomainNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Email Salah. \nContoh : namaemail@intra.bca atau namaemail@bca.co.id.
        /// </summary>
        internal static string WrongEmailFormat {
            get {
                return ResourceManager.GetString("WrongEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harap masukan alamat email sesuai format.
        /// </summary>
        internal static string WrongEmailSearch {
            get {
                return ResourceManager.GetString("WrongEmailSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword WSID harus diisi.
        /// </summary>
        internal static string WsidMandatoryKeyword {
            get {
                return ResourceManager.GetString("WsidMandatoryKeyword", resourceCulture);
            }
        }
    }
}
