//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductTransactions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductTransactions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ProductTransactions", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanggal awal harus lebih kecil dari pada tanggal akhir.
        /// </summary>
        internal static string DateIsNotValid {
            get {
                return ResourceManager.GetString("DateIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kedua field Tanggal harus diisi value yang berbeda.
        /// </summary>
        internal static string DifferentDate {
            get {
                return ResourceManager.GetString("DifferentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field No Rekening harus diisi.
        /// </summary>
        internal static string MandatoryAccountNo {
            get {
                return ResourceManager.GetString("MandatoryAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field No Kartu ATM harus diisi.
        /// </summary>
        internal static string MandatoryATMCardNo {
            get {
                return ResourceManager.GetString("MandatoryATMCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field No Kartu harus diisi.
        /// </summary>
        internal static string MandatoryCardNo {
            get {
                return ResourceManager.GetString("MandatoryCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field No Kartu / No Rekening harus diisi.
        /// </summary>
        internal static string MandatoryCardNo_AccountNo {
            get {
                return ResourceManager.GetString("MandatoryCardNo_AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field No Kartu / Dari Rekening harus diisi.
        /// </summary>
        internal static string MandatoryCardNo_FromAccount {
            get {
                return ResourceManager.GetString("MandatoryCardNo_FromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Tanggal harus diisi.
        /// </summary>
        internal static string MandatoryDate {
            get {
                return ResourceManager.GetString("MandatoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field FIID harus diisi.
        /// </summary>
        internal static string MandatoryFIID {
            get {
                return ResourceManager.GetString("MandatoryFIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Dari Rekening harus diisi.
        /// </summary>
        internal static string MandatoryFromAccount {
            get {
                return ResourceManager.GetString("MandatoryFromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field LNET harus diisi.
        /// </summary>
        internal static string MandatoryLNET {
            get {
                return ResourceManager.GetString("MandatoryLNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Request ID harus diisi.
        /// </summary>
        internal static string MandatoryRequestID {
            get {
                return ResourceManager.GetString("MandatoryRequestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Tanggal awal harus diisi.
        /// </summary>
        internal static string MandatoryStartDate {
            get {
                return ResourceManager.GetString("MandatoryStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Tgl Trx harus diisi.
        /// </summary>
        internal static string MandatoryTglTrx {
            get {
                return ResourceManager.GetString("MandatoryTglTrx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Request ID harus angka.
        /// </summary>
        internal static string NumericRequestID {
            get {
                return ResourceManager.GetString("NumericRequestID", resourceCulture);
            }
        }
    }
}
