//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Queue", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Business Unit harus diisi.
        /// </summary>
        internal static string MandatoryQueueBU {
            get {
                return ResourceManager.GetString("MandatoryQueueBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Workgroup tersebut tidak ada.
        /// </summary>
        internal static string MandatoryQueueBU2 {
            get {
                return ResourceManager.GetString("MandatoryQueueBU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Workgroup Name harus diisi.
        /// </summary>
        internal static string MandatoryQueueName {
            get {
                return ResourceManager.GetString("MandatoryQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Owner harus diisi.
        /// </summary>
        internal static string MandatoryQueueOwner {
            get {
                return ResourceManager.GetString("MandatoryQueueOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Owner tersebut tidak ada.
        /// </summary>
        internal static string MandatoryQueueOwner2 {
            get {
                return ResourceManager.GetString("MandatoryQueueOwner2", resourceCulture);
            }
        }
    }
}
