//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportFilters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportFilters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ReportFilters", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter gagal di hapus.
        /// </summary>
        internal static string FilterDelFail {
            get {
                return ResourceManager.GetString("FilterDelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter berhasil di hapus.
        /// </summary>
        internal static string FilterDelSuccess {
            get {
                return ResourceManager.GetString("FilterDelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter gagal di tambahkan dalam Report.
        /// </summary>
        internal static string FilterFail {
            get {
                return ResourceManager.GetString("FilterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penambahan Master Filter dengan Nama Tersebut tidak di ijinkan!.
        /// </summary>
        internal static string FilterForbidden {
            get {
                return ResourceManager.GetString("FilterForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter sudah ditambahkan dalam Report.
        /// </summary>
        internal static string FilterSame {
            get {
                return ResourceManager.GetString("FilterSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter berhasil di tambahkan dalam Report.
        /// </summary>
        internal static string FilterSuccess {
            get {
                return ResourceManager.GetString("FilterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Type belum di pilih.
        /// </summary>
        internal static string TypeMandatory {
            get {
                return ResourceManager.GetString("TypeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Type belum di isi.
        /// </summary>
        internal static string TypeMandatory2 {
            get {
                return ResourceManager.GetString("TypeMandatory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value harus di isi.
        /// </summary>
        internal static string ValueMandatory {
            get {
                return ResourceManager.GetString("ValueMandatory", resourceCulture);
            }
        }
    }
}
