//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RequestCreationMatrix {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestCreationMatrix() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RequestCreationMatrix", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for Account Code.
        /// </summary>
        internal static string Alert_ProvideAccountCode {
            get {
                return ResourceManager.GetString("Alert_ProvideAccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for Category.
        /// </summary>
        internal static string Alert_ProvideCategory {
            get {
                return ResourceManager.GetString("Alert_ProvideCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for E-Banking &amp; Products.
        /// </summary>
        internal static string Alert_ProvideEBanking {
            get {
                return ResourceManager.GetString("Alert_ProvideEBanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for New Status.
        /// </summary>
        internal static string Alert_ProvideNewStatus {
            get {
                return ResourceManager.GetString("Alert_ProvideNewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for Previous Status.
        /// </summary>
        internal static string Alert_ProvidePreviousStatus {
            get {
                return ResourceManager.GetString("Alert_ProvidePreviousStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for Product.
        /// </summary>
        internal static string Alert_ProvideProduct {
            get {
                return ResourceManager.GetString("Alert_ProvideProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for Request Status.
        /// </summary>
        internal static string Alert_ProvideRequestStatus {
            get {
                return ResourceManager.GetString("Alert_ProvideRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for Status Name.
        /// </summary>
        internal static string Alert_ProvideStatusName {
            get {
                return ResourceManager.GetString("Alert_ProvideStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for Summary.
        /// </summary>
        internal static string Alert_ProvideSummary {
            get {
                return ResourceManager.GetString("Alert_ProvideSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no longer session. Please re-login..
        /// </summary>
        internal static string Alert_SessionIsNull {
            get {
                return ResourceManager.GetString("Alert_SessionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keluhan Nasabah sudah berhasil disimpan.
        /// </summary>
        internal static string Alert_SubmissionSuccess {
            get {
                return ResourceManager.GetString("Alert_SubmissionSuccess", resourceCulture);
            }
        }
    }
}
