//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Request {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Request() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Request", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field branch tidak diisi dengan benar.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Action tidak diisi dengan benar.
        /// </summary>
        internal static string Cause {
            get {
                return ResourceManager.GetString("Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Referal Request tidak diisi dengan benar.
        /// </summary>
        internal static string RefRequest {
            get {
                return ResourceManager.GetString("RefRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Interaction Count harus diisi dengan numerik.
        /// </summary>
        internal static string RequestInteractionCountNumber {
            get {
                return ResourceManager.GetString("RequestInteractionCountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Address harus diisi.
        /// </summary>
        internal static string RequestMandatoryAddress {
            get {
                return ResourceManager.GetString("RequestMandatoryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Address1 harus diisi.
        /// </summary>
        internal static string RequestMandatoryAddress1 {
            get {
                return ResourceManager.GetString("RequestMandatoryAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Address2 harus diisi.
        /// </summary>
        internal static string RequestMandatoryAddress2 {
            get {
                return ResourceManager.GetString("RequestMandatoryAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Category harus diisi.
        /// </summary>
        internal static string RequestMandatoryCategory {
            get {
                return ResourceManager.GetString("RequestMandatoryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Category tersebut tidak ada.
        /// </summary>
        internal static string RequestMandatoryCategory2 {
            get {
                return ResourceManager.GetString("RequestMandatoryCategory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Channel harus diisi.
        /// </summary>
        internal static string RequestMandatoryChannel {
            get {
                return ResourceManager.GetString("RequestMandatoryChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field City harus diisi.
        /// </summary>
        internal static string RequestMandatoryCity {
            get {
                return ResourceManager.GetString("RequestMandatoryCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Customer harus diisi.
        /// </summary>
        internal static string RequestMandatoryCustomer {
            get {
                return ResourceManager.GetString("RequestMandatoryCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Customer tersebut tidak ada.
        /// </summary>
        internal static string RequestMandatoryCustomer2 {
            get {
                return ResourceManager.GetString("RequestMandatoryCustomer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Owner harus diisi.
        /// </summary>
        internal static string RequestMandatoryOwner {
            get {
                return ResourceManager.GetString("RequestMandatoryOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Phone harus diisi.
        /// </summary>
        internal static string RequestMandatoryPhone {
            get {
                return ResourceManager.GetString("RequestMandatoryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Product harus diisi.
        /// </summary>
        internal static string RequestMandatoryProduct {
            get {
                return ResourceManager.GetString("RequestMandatoryProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Product tersebut tidak ada.
        /// </summary>
        internal static string RequestMandatoryProduct2 {
            get {
                return ResourceManager.GetString("RequestMandatoryProduct2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Summary harus diisi.
        /// </summary>
        internal static string RequestMandatorySummary {
            get {
                return ResourceManager.GetString("RequestMandatorySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Zip harus diisi.
        /// </summary>
        internal static string RequestMandatoryZip {
            get {
                return ResourceManager.GetString("RequestMandatoryZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Phone harus diisi dengan numerik.
        /// </summary>
        internal static string RequestNumericCommunicationPhoneNumber {
            get {
                return ResourceManager.GetString("RequestNumericCommunicationPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Incoming Phone Number harus diisi dengan numerik.
        /// </summary>
        internal static string RequestNumericIncomingPhoneNumber {
            get {
                return ResourceManager.GetString("RequestNumericIncomingPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keluhan ini hanya dapat di proses melalui Halo BCA.
        /// </summary>
        internal static string RequestWorkgroup {
            get {
                return ResourceManager.GetString("RequestWorkgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Zip harus  5 digit numerik.
        /// </summary>
        internal static string RequestZipLength {
            get {
                return ResourceManager.GetString("RequestZipLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field WSID tidak diisi dengan benar.
        /// </summary>
        internal static string WSID {
            get {
                return ResourceManager.GetString("WSID", resourceCulture);
            }
        }
    }
}
