//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceLevel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceLevel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ServiceLevel", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Category harus diisi.
        /// </summary>
        internal static string SLAMandatoryCategory {
            get {
                return ResourceManager.GetString("SLAMandatoryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field SLA Days harus diisi.
        /// </summary>
        internal static string SLAMandatoryDays {
            get {
                return ResourceManager.GetString("SLAMandatoryDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Product harus diisi.
        /// </summary>
        internal static string SLAMandatoryProduct {
            get {
                return ResourceManager.GetString("SLAMandatoryProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Workgroup harus diisi.
        /// </summary>
        internal static string SLAMandatroyWG {
            get {
                return ResourceManager.GetString("SLAMandatroyWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Level sudah didaftarkan sebelumnya.
        /// </summary>
        internal static string SLASame {
            get {
                return ResourceManager.GetString("SLASame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmentasi atau kota berhasil ditambahkan.
        /// </summary>
        internal static string SLASegmentSuccess {
            get {
                return ResourceManager.GetString("SLASegmentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Level berhasil didaftarkan.
        /// </summary>
        internal static string SLASuccess {
            get {
                return ResourceManager.GetString("SLASuccess", resourceCulture);
            }
        }
    }
}
