//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StaticData", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRMUser.
        /// </summary>
        internal static string AdminHomeController {
            get {
                return ResourceManager.GetString("AdminHomeController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Admin.
        /// </summary>
        internal static string AdminRoleName {
            get {
                return ResourceManager.GetString("AdminRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabang.
        /// </summary>
        internal static string BusinessUnitID_BranchName {
            get {
                return ResourceManager.GetString("BusinessUnitID_BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string HomeController {
            get {
                return ResourceManager.GetString("HomeController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAdministration.
        /// </summary>
        internal static string LocalAdminAction {
            get {
                return ResourceManager.GetString("LocalAdminAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRMReport.
        /// </summary>
        internal static string ReportHomeController {
            get {
                return ResourceManager.GetString("ReportHomeController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestManagement.
        /// </summary>
        internal static string SPVAgentCabangAction {
            get {
                return ResourceManager.GetString("SPVAgentCabangAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPV Agent Cabang.
        /// </summary>
        internal static string SPVAgentCabangRole {
            get {
                return ResourceManager.GetString("SPVAgentCabangRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRMCustomer.
        /// </summary>
        internal static string UserHomeController {
            get {
                return ResourceManager.GetString("UserHomeController", resourceCulture);
            }
        }
    }
}
