//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCRMReport.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCA_MSCRMEntities : DbContext
    {
        public BCA_MSCRMEntities()
            : base("name=BCA_MSCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Request> Requests { get; set; }
        public DbSet<SystemUser> SystemUsers { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<CallWrapUpReport> CallWrapUpReports { get; set; }
    }
}
