//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCRMReport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public System.Guid TaskID { get; set; }
        public Nullable<System.Guid> PartyUserID { get; set; }
        public string PartyUserName { get; set; }
        public string TaskNumber { get; set; }
        public string CCQID { get; set; }
        public string RequestTicketNumber { get; set; }
        public string Subject { get; set; }
        public string Regarding { get; set; }
        public Nullable<int> RequestStatusCode { get; set; }
        public string RequestStatusLabel { get; set; }
        public Nullable<int> TaskStatus { get; set; }
        public string TaskStatusLabel { get; set; }
        public int ActivityStatus { get; set; }
        public string ActivityStatusLabel { get; set; }
        public Nullable<int> Priority { get; set; }
        public string PriorityLabel { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.Guid> OwnerID { get; set; }
        public string OwnerName { get; set; }
        public Nullable<System.Guid> WorkGroupID { get; set; }
        public string WorkGroupName { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedByName { get; set; }
        public int DeletionStateCode { get; set; }
        public Nullable<System.Guid> BusinessUnitID { get; set; }
        public Nullable<System.Guid> RequestID { get; set; }
        public System.Guid Pointer_ActivityId { get; set; }
    }
}
