//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCopy
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMAcitivityPointer_ActivityType
    {
        public string EntityName { get; set; }
        public string AttributeName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> AttributeValue { get; set; }
        public string Label { get; set; }
        public System.Guid StringMapID { get; set; }
    }
}
